### PR TITLE
Port to Python 3

### PR DESCRIPTION
**Pull request by anmol27katyani**
- Updated files
- The ported activity gets stuck on starting

### CODE REVIEW

**Comment by anmol27katyani** [comment]
@quozl Please guide
The ported activity doesn't seem to respond

**Comment by quozl** [comment]
Use a debugger.

Verify that the activity runs for you before your port; checkout 79dec3b6611b8bd885909e78be2e5cbd7449cd62, test it starts, and then return to your branch.

Verify that another ported activity runs properly in your environment.  There are several to choose from in the pending pull requests for the [Port to Python 3 project](https://github.com/orgs/sugarlabs/projects/1).

On the off-chance it was something to do with the `aplay.py` module that I'd recently written and tested, I did a test with Python3 like this;

```python3
#!/usr/bin/python3

import os
import gi
from gi.repository import GLib
from utils.aplay import aplay

loop = GLib.MainLoop()

def cb():
    aplay.play(os.path.join(os.getcwd(), 'sounds/es/iglesia.ogg'))
    return False

GLib.idle_add(cb)
GLib.timeout_add(1300, loop.quit)
loop.run()
```

It worked fine, so that means it isn't the `aplay.py` module.

**Comment by anmol27katyani** [comment]
@quozl the activity runs fine before the port and yes, I think it was environment issue earlier.

**Comment by rhl-bthr** [comment]
Thanks. 
Tested. The activity fails to start

Logs:
```shell
Traceback (most recent call last):
  File "/usr/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 215, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 49, in create_activity_instance
    activity = constructor(handle)
  File "/usr/share/sugar/activities/AEIOU/aeiou.py", line 81, in __init__
    parent=self)
  File "/usr/share/sugar/activities/AEIOU/page.py", line 94, in __init__
    self._colors[0]))))
  File "/usr/share/sugar/activities/AEIOU/page.py", line 380, in svg_str_to_pixbuf
    pl.write(svg_string)
TypeError: Item 0: Must be number, not str
1529726193.711494 DEBUG root: _cleanup_temp_files
```

**Comment by anmol27katyani** [comment]
What do you suggest @Pro-Panda ?
Any tips will be appreciated.

**Comment by quozl** [comment]
Use a debugger?

**Comment by rhl-bthr** [comment]
@octamois 
My usual approach is to go through the traceback to find the source of the error.

**Comment by rhl-bthr** [comment]
Thanks. Tested. Doesn't work

Here are the logs:
```shell
Traceback (most recent call last):
  File "/usr/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 218, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 49, in create_activity_instance
    activity = constructor(handle)
  File "/home/pro-panda/AEIOU/aeiou.py", line 81, in __init__
    parent=self)
  File "/home/pro-panda/AEIOU/page.py", line 94, in __init__
    self._colors[0]))))
  File "/home/pro-panda/AEIOU/page.py", line 380, in svg_str_to_pixbuf
    pl.encode()
AttributeError: 'PixbufLoader' object has no attribute 'encode'

(sugar-activity3:14608): GdkPixbuf-WARNING **: GdkPixbufLoader finalized without calling gdk_pixbuf_loader_close() - this is not allowed. You must explicitly end the data stream to the loader before dropping the last reference.
```

Please test before commit

**Comment by rhl-bthr** [comment]
Stale; Needs more work.

@octamois if you plan to fix the same, please reopen the PR with the fixes

**Pull request closed without merging**
