### PR TITLE
Fixing files for deployment of ASLOv3 

### PR DESCRIPTION
**Pull request by vipulgupta2048**
In reference to the project in GSoC 2018,
For the successful deployment of ASLOv3, some files and activity.info need to be added/fixed/updated to present correct metadata on the website.

Updated Parameters:- 
1. `website`
2. `repository`

Please review the same, and suggest any changes that are required.

### CODE REVIEW

**Comment by rhl-bthr** [comment]
Thank you. 
Reviewed.

`website` and `category` are deprecated, please use `url` and `tags` instead 
(While these are valid, they are not encouraged)

Reference: [sugar-toolkit/@47563e6](https://github.com/sugarlabs/sugar-toolkit-gtk3/commit/47563e678fdcecb7d80f70abf743e182cfb8af17)

**Comment by vipulgupta2048** [comment]
@Pro-Panda It appears to me, that I have pushed the wrong branch. Let me make the necessary changes. So sorry.

**Comment by rhl-bthr** [comment]
Thanks.
Reviewed again

**Comment by rhl-bthr** [comment]
The commit message was not consistent. I have taken care of the same while squashing your commit.

**Comment by vipulgupta2048** [comment]
Will take care of the same next time onwards.

**Pull request merged**
