### PR TITLE
fix ubuntu audio

### LINKED ISSUE #7: utils/play_audio problem with subprocess
Fails for Ubuntu 16.04 sucrose. The following code corrects the problem:

from subprocess import call

def play_audio_from_file(file_path):
    call('gst-launch-0.10 playbin uri=file://'+file_path().strip(), shell=True)

### PR DESCRIPTION
**Pull request by yell0wfl4sh**
fixes #7 
All audio works fine in ubuntu. Added updated utils files from I Know ABCs repository.
@quozl  please review!

### CODE REVIEW

**Comment by quozl** [comment]
Reviewed your play_audio.py.  It is very complicated, and has much more code than is required.  Please use something simpler, such as this use of _playbin_ element; https://github.com/quozl/record-activity/blob/gtk3/aplay.py

Unless there's something in the complication that is needed?  What do you think?

**Comment by quozl** [comment]
Please review and test 0899d7b.

Other activities that use the same module are;
* https://github.com/sugarlabs/lettermatch/blob/2e9818d1207e2621b03f758fe585f9c55dc7adfa/utils/play_audio.py
* https://github.com/sugarlabs/portfolio-activity/blob/e717efab11b3aff44047abbbacee93dec021af96/gplay.py
* https://github.com/sugarlabs/iknowmyabcs/blob/fd7b3af909c10a9f3524b3bccde71e1923019d60/utils/play_audio.py

Other activities that call out to a subprocess are;
* https://github.com/sugarlabs/fractionbounce/blob/f8ff214d64ab3b47b5987a1e644a5c15927a7843/play_audio.py
* https://github.com/sugarlabs/i-can-read-activity/blob/01611cb95bbf6482ada9b2dff1492f1f049df46b/utils/play_audio.py
* https://github.com/sugarlabs/locosugar/blob/d368103ee52a2ff56bdd220fcf97b5079f5cc0ce/play_audio.py
* https://github.com/sugarlabs/story/blob/5c90577f79bafbc2d8a65f1cc49d49b6e66c1358/utils.py#L45

Yet another design including video playback is here;
* https://github.com/sugarlabs/amazonas-activity/blob/ab07994c9cbd0475fe1b8a23401233ec0b61abfa/TurtleArt/tagplay.py
* https://github.com/sugarlabs/activity-turtle-flags/blob/ac20359849272efa9c1978d979218b5782c21523/TurtleArt/tagplay.py
* https://github.com/sugarlabs/activity-turtle-confusion/blob/2619b5235caec28d34da55a211e651e9e5eeac00/TurtleArt/tagplay.py
* https://github.com/sugarlabs/turtleart-activity/blob/4bb1e8fe75a463018286b98749523018af62e1a9/TurtleArt/tagplay.py

**Comment by yell0wfl4sh** [comment]
Thanks. Reviewed, works fine. 
Some errors logged during running the activity:
```
Traceback (most recent call last):
  File "/home/yash/testgsox/AEIOU/page.py", line 244, in _play_target_sound
    self._media_data[self.target][0]))
  File "/home/yash/testgsox/AEIOU/utils/aplay.py", line 28, in aplay
    player.set_state(Gst.State.NULL)
AttributeError: 'NoneType' object has no attribute 'set_state'

```

**Comment by quozl** [comment]
Thanks for review.  The error you paste could occur if activity close was in progress when another sound was requested for playing.  I've coded for that possibility now.

Also, I rewrote the module as a class, and used Python's Queue type to fix another problem.  See d8d5c11.

**Comment by yell0wfl4sh** [comment]
Reviewed. Great work James! :)

**Pull request merged**
